# Builds a .NET framework project in Release mode when a new release is created
# and uploads the build results to the newly created release
# then updates update.xml (NOT IMPLEMENTED YET)
# assumes the version in Properties/AssemblyInfo.cs has already been updated
name: Publish release

env:
  projectName: FunkeySelectorGUI
  projectFolder: FunkeySelector
  solutionFile: FunkeySelector.sln

on:
  release: 
    types:
      - released

jobs:
  publish:
    permissions:
      contents: write
      id-token: write
    strategy:
      matrix:
        configuration: [ Release ]
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup git configuration
        run: |
          git config user.name "Github Actions Bot"
          git config user.email "<>"
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
      
      - name: Restore Packages
        run: nuget restore ${{ env.solutionFile }}
      
      - name: Build solution
        run: msbuild ${{ env.solutionFile }} -t:rebuild -property:Configuration=${{ matrix.configuration }}
      
      - name: Get version from release name
        id: version
        uses: mad9000/actions-find-and-replace-string@4
        with:
          source: "${{ github.event.release.tag_name }}"
          find: "v"
          replace: ""
      
      - name: Upload the build results as an artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.projectFolder }}/bin/${{ matrix.configuration }}/*
          name: ${{ env.projectName }}.${{ github.event.release.tag_name }}.${{ matrix.configuration }}
      
      - name: Upload build results to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ env.projectFolder }}/bin/${{ matrix.configuration }}/FunkeySelector.exe
      
      - name: Get file size of FunkeySelectorGUI.exe
        id: filesize
        run: echo "FILESIZE=$((Get-Item FunkeySelector.exe).length)" >> $GITHUB_OUTPUT
      
      - name: Update update.xml
        run: |
          echo '<update version="${{ steps.version.outputs.value }}" name="${{ github.event.release.name }}" size="${{ steps.filesize.outputs.FILESIZE }}" url="https://github.com/GittyMac/FunkeySelectorGUI/releases/download/${{ github.event.release.tag_name }}/FunkeySelectorGUI.exe" />' > update.xml
      
      - name: Push the changes made to update.xml
        run: |
          git add update.xml
          git commit -m "chore(update): update update.xml"
          git push origin master
